---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camera-app-prd
  namespace: thanh-prd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/dvanthanh1992/test-dev/prd/helm-charts/
    chart: thanh-camera-infra
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: thanh-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
