apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camera-app-prd
  namespace: thanh-prd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/dvanthanh1992
      chart: thanh-camera-app-chart
      targetRevision: 0.1.0
      helm:
        passCredentials: false
        valueFiles:
          - $values/helm-values/values-prd.yml

    - repoURL: "https://github.com/dvanthanh1992/test-dev"
      targetRevision: prd
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: thanh-prd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
