---

replicaCount: 1
env:
  STAGE_ENVIRONMENT: "DEV-ENVIRONMENT"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8888

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http
